### ISSUE TITLE
BUG: Tunnel Borked

### ISSUE THREAD

**Issue by marina8888** [ultrahorizon/UH-Enterprise-Docs#2] opened 2019-09-30 22:50 UTC
Cannot reconnect to network without disconnecting from UH Enterprise first. 

**To Reproduce**
1. Connect to UH Enterprise, fast server. 
2. Browse internet normally (on chrome?) for approx 1 hour. The error will repeat every hour (approx.) of browsing. 

**Expected behavior**
Internet becomes no longer accessible until you disconnect from UH Enterprise, showing a page "your connection was interrupted". Once you are disconnected, the internet is accessible again and it is possible to reconnect to UH Enterprise.
4. The Error will repeat after another (approx) hour of browsing while connected to UH Enterprise. 

**Screenshots**
<img width="1440" alt="Screenshot 2019-09-30 at 23 46 45" src="https://user-images.githubusercontent.com/38610356/65922280-b164e300-e3dc-11e9-90a7-b8e371f7c0e5.png">
<img width="1412" alt="Screenshot 2019-09-30 at 23 47 01" src="https://user-images.githubusercontent.com/38610356/65922285-b32ea680-e3dc-11e9-9fc5-d7748c55d3df.png">
<img width="1423" alt="Screenshot 2019-09-30 at 23 47 15" src="https://user-images.githubusercontent.com/38610356/65922287-b6c22d80-e3dc-11e9-8249-03cbaf4e121e.png">
<img width="1412" alt="Screenshot 2019-09-30 at 23 47 27" src="https://user-images.githubusercontent.com/38610356/65922292-b9248780-e3dc-11e9-848c-cbc5ce45e54d.png">

**Web Console (please complete the following information):**
 - macOS
 - chrome
 - Version 1.0.0

**Additional context**
Error witnessed by James Webb at 10.15-10.25 p.m. 30/09/2019
Video not attachable but emailed directly. 

Thank you,
Marina

**Comment by jwsi** [comment] 2019-09-30 23:18
Ok so this looks like a potential reachability issue (which **should** be picked up and fixed in iOS testing) and can be caused by a WAN failure (which I noticed when macOS WiFi icon flashed). Essentially, if WAN fails, the VPN should reconnect and bind to a new available address and port pair. If this process does not happen, the tunnel will remain unresponsive.

On the other hand, since this seems to be repetative (once every hour), it could instead link to a renegotiation issue. Data channel encryption keys are changed every hour and this renegotiation process could be failing. I will search for any exception in the logs for you at this time and report any feedback here.

**Comment by marina8888** [comment] 2019-09-30 23:22
Just spoke to mum and she said BT hub disconnects briefly every hour or so at our house… please feel free to assume that disconnection itself is not linked to the uh enterprise. 

Marina

**Comment by jwsi** [comment] 2019-09-30 23:27
No this is actually an issue with renegotiation. Logs are showing many issues with decrypting the obfuscation keys.

@AnthonyWharton for reference server side:
```
TLS Error: tls-crypt unwrapping failed
tls-crypt unwrap error: bad packet ID (may be a replay): [ #8 / time = (1569877927) Mon Sep 30 22:12:07 2019 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings
```
Think this might be a macOS client issue...

**Comment by jwsi** [comment] 2019-10-01 10:30
This has now been fixed. UH Enterprise clients now control the key renegotation time instead of the server which presented issues. Each client now defines:

- How long each data channel encryption key can be used for
- Time taken to renegotiate the key
- Transition time between old key and new key

**Closed by jwsi** 2019-10-01 10:30 UTC
Labels: bug
